name: pdup
version: 0.0.0.1

dependencies:
  - base
  - rio

default-extensions:
  - BangPatterns
  - DataKinds
  - DeriveAnyClass
  - DeriveFoldable
  - DeriveFunctor
  - DeriveGeneric
  - DeriveLift
  - DeriveTraversable
  - DerivingStrategies
  - FlexibleContexts
  - FlexibleInstances
  - GADTs
  - GeneralizedNewtypeDeriving
  - LambdaCase
  - MultiParamTypeClasses
  - NoImplicitPrelude
  - NoMonomorphismRestriction
  - OverloadedStrings
  - RankNTypes
  - RecordWildCards
  - ScopedTypeVariables
  - StandaloneDeriving
  - TypeApplications
  - TypeFamilies

library:
  source-dirs: library
  dependencies:
    - aeson
    - bytestring
    - conduit
    - errors
    - http-client
    - http-conduit
    - http-link-header
    - http-types
    - iso8601-time
    - optparse-applicative
    - rampart
    - retry
    - text

executables:
  pdup:
    main: Main.hs
    source-dirs: executables
    dependencies:
      - conduit
      - errors
      - load-env
      - pdup

tests:
  spec:
    main: Spec.hs
    source-dirs: test
    dependencies:
      - QuickCheck
      - hspec
      - pdup
      - quickcheck-instances
